"use client";

import { useMemo, useState } from "react";
import { Button, Card, Typography } from "shivanya-ui";
import { buildAnalytics } from "@/lib/analytics";
import { getState } from "@/lib/store";
import { Page } from "./Page";

const labels: Record<string,string> = { traffic:"Traffic Acquisition", referrers:"Referrers", browsers:"Browsers", devices:"Devices", countries:"Countries", cities:"Cities", isps:"ISPs", ips:"IPs", sessions:"Sessions", operating-systems:"Operating Systems" };

export function AnalyticsPage({ dimension = "traffic" }: { dimension?: string }) {
  const [live, setLive] = useState(false);
  const analytics = useMemo(() => buildAnalytics(getState()), [live]);
  const data = dimension === "referrers" ? analytics.referrers : dimension === "browsers" ? analytics.browsers : dimension === "devices" ? analytics.devices : dimension === "countries" ? analytics.countries : dimension === "cities" ? analytics.cities : dimension === "isps" ? analytics.isps : dimension === "ips" ? analytics.ips : analytics.traffic;
  return <Page title={labels[dimension] ?? "Analytics"} description="Explore analytics generated by the shared local analytics adapter." actions={<Button variant={live ? "primary" : "outline"} onClick={() => setLive(!live)}>{live ? "Live" : "Live mode"}</Button>}>
    <div className="admin-grid">
      <Card><Typography variant="caption" color="secondary">Total</Typography><div className="admin-stat-value">{data.reduce((n,p)=>n+p.value,0)}</div></Card>
      <Card><Typography variant="caption" color="secondary">Sources</Typography><div className="admin-stat-value">{data.length}</div></Card>
      <Card><Typography variant="caption" color="secondary">Top</Typography><div className="admin-stat-value">{data[0]?.label ?? "—"}</div></Card>
      <Card><Typography variant="caption" color="secondary">Status</Typography><div className="admin-stat-value">{live ? "Live" : "Ready"}</div></Card>
    </div>
    <div className="admin-card"><Typography as="h2" variant="h4" weight="semibold">Breakdown</Typography><div className="admin-list">{data.map((item)=><div className="admin-row" key={item.label}><span>{item.label}</span><strong>{item.value}</strong></div>)}</div></div>
  </Page>;
}